import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import logo from '../assets/logo.svg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico?v=2" />
      </Head>
      <main className={styles.main}>
        <h3 className={styles.pre_title}>Nursing</h3>
        <h1 className={styles.title}>
          Diagnos<span>IC</span>
        </h1>
        <div className={styles.image}>
          <img inline="true" src={logo} alt="heart with pulse" />
        </div>
        <p className={styles.subtitle}>
          DIAGNÓSTICOS DE ENFERMAGENS EM INSUFICIÊNCIA CARDÍACA
        </p>
        <button className={styles.button}>Começar</button>
      </main>
    </div>
  )
}
