import React from 'react'
import Head from 'next/head'
import Header from '../../components/header/index'
import Checkbox from '../../components/utils/checkbox/checkbox'
import Button from '../../components/utils/button/button'
import Footer from '../../components/footer/index'
import styles from '../../styles/Domain.module.scss'

import api from '../../services/api/api'

export async function getStaticPaths() {
  const response = await api.get('domain')

  const ids = response.data

  const paths = ids.map((path) => {
    return {
      params: {
        id: `${path.id}`,
      },
    }
  })

  return {
    paths,
    fallback: false,
  }
}

export async function getStaticProps(context) {
  const id = context.params.id
  const { data: domain } = await api.get(`domain/${id}`)
  const { data: ids } = await api.get('domain')
  const size = ids.length

  const response = {
    domain,
    size,
  }
  return {
    props: response,
  }
}

function pages(props) {
  const handleBackButton = (id) => {
    return id === 1 ? '/' : (id - 1).toString()
  }

  const handleNextButton = (id) => {
    return id < props.size ? (id + 1).toString() : '/'
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico?v=2" />
      </Head>
      <Header />
      <main className={styles.container}>
        <div className={styles.content}>
          <div className={styles.header}>
            <h5 className={styles.name}>{props.domain.name}</h5>
            <h6 className={styles.definition}>{props.domain.definition}</h6>
          </div>
          <ul className={styles.checklist}>
            {props.domain.symptoms.map((d) => (
              <li key={d.id} className={styles.listitem}>
                <Checkbox domain={d}></Checkbox>
              </li>
            ))}
          </ul>

          <div className={styles.buttons}>
            <Button
              path={handleBackButton(props.domain.id)}
              background="#E31722"
              color="#FFF"
            >
              Voltar
            </Button>
            <Button
              path={handleNextButton(props.domain.id)}
              background="#E31722"
              color="#FFF"
            >
              Próximo
            </Button>
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}

export default pages
